appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c33c5ad87b5930700c3ebbd
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: S/a8XO9VHw+9J7EXJi8Fh8HrZxRWiOIa5ynVmOmFgpd5c1ZTk5B1WSrpaN20hsAFeI9gjqWV59rQtj0lQJewVQ+iD2Qs/HWiT/dxJK68XqAIlgQ6dAtMsD+sBZuDQpF/F2Jsv2lQcjuvvaLbDowyNmE3s0brJkZdkaKbxXMgtg0AeDZ2y3yRlPTFhPWgd36bnnVJnb/7wrTmbvWpVxhD4qyjxjq1t1lw84Qd6RTjfNUOAXb00p3zT/KPFyS5utKHIxqdVobhZ+vyRFIRn1IJMHA2K5I3MDnlpei/bZU+7qYojLcBIPt/hoCGhvSSpEINMRkpXlh2qS1LyBRhEEBKxIwOSmuJlBewmCvrCw12tAIJzp4cRZVDoIHXDvbClXh7j/TumjrSTo1HhEIr5a7L9X4pKLbpXjxlFX3VviqKI77g4/YwGGkqnZw79u57GUCuQQWHyAJnt4JAIQbbM7kATQhfsBxr7Byq0LoL55VRBPJFt9m1TVmVKawxMG+UzYPcdRmUIDol1IgYVvDhOH2wnEmvRJD8/QG0jgeLvq6nzo4qAqM8lNQe/HkYfASGlKeaRZzevI3NcczwPse7S4Ypzj2fQo8w74jGwq14zoNRwqC8DZGjNPOFWMZx2+iwA9311y88UIST86pddBfxLABN9WD8by1KrD94yWQrWtw5HS4=}
